### ISSUE TITLE
Use bitmasks to simplify key purposes

### ISSUE THREAD

**Issue by tyleryasaka** [ERC725Alliance/erc725#12]
I propose the following change to ERC734 (as defined in [this doc](https://github.com/ERC725Alliance/erc725/blob/master/docs/ERC-734.md)):

Allow each key to only have a single purpose value. This single purpose would actually represent multiple purposes by convention, using bitmasks.

For example:
- `...001`: MANAGEMENT
- `...010`: EXECUTION

Thus a key with a purpose of `1`, `3`, or `5`, etc. would be a valid management key. A key with a purpose of `2`, `3`, `6`, or, `7`, etc. would be a valid execution key. Thus `1` would be a management key, but not an execution key. `2` would be an execution key, but not a management key. `3` would be both a management and execution key.

The rationale of this technique is that it would give us the full flexibility and power of having multiple purposes per key, minus the overhead of managing an array of purposes in solidity. Bitmasks can be implemented efficiently in solidity.

I'm not clear on whether `uint256` or `bytes32` would make more sense here. Seems like they would both work: https://ethereum.stackexchange.com/questions/28360/where-is-the-barrier-between-using-uint256-and-bytes32

I think it would also make more sense to think of keys being set rather than added. You could call `setKey` to either add a key or update an existing key.

The updated interface would be something like :

```
pragma solidity ^0.4.18;

contract ERC725 {
pragma solidity ^0.4.18;

contract ERC725 {

    event KeySet(bytes32 indexed key, uint256 indexed purpose, uint256 indexed keyType);
    event KeyRemoved(bytes32 indexed key, uint256 indexed purpose, uint256 indexed keyType);
    event ExecutionRequested(uint256 indexed executionId, address indexed to, uint256 indexed value, bytes data);
    event Executed(uint256 indexed executionId, address indexed to, uint256 indexed value, bytes data);
    event Approved(uint256 indexed executionId, bool approved);
    event KeysRequiredChanged(uint256 purpose, uint256 number);

    function getKey(bytes32 _key) public constant returns(uint256 purpose, uint256 keyType, bytes32 key);
    function keyHasPurpose(bytes32 _key, uint256 _purpose) public constant returns (bool exists);
    function setKey(bytes32 _key, uint256 _purpose, uint256 _keyType) public returns (bool success);
    function removeKey(bytes32 _key) public returns (bool success);
    function changeKeysRequired(uint256 purpose, uint256 number) external;
    function getKeysRequired(uint256 purpose) external view returns(uint256);
    function execute(address _to, uint256 _value, bytes _data) public returns (uint256 executionId);
    function approve(uint256 _id, bool _approve) public returns (bool success);
}
```

Thoughts?

**Comment by filiplazovic** [comment]
Nice, i'm working on implementing this 👍

**Comment by filiplazovic** [comment]
Do we need `removeKey`? Can everything be done in `setKey`?

**Comment by tyleryasaka** [comment]
@filiplazovic Yeah, everything could be done with `setKey`. We could keep `removeKey` just as a convenience, but it's not needed.

**Comment by tyleryasaka** [comment]
status update: just merged the code from @filiplazovic to implement this. 😄
