### ISSUE TITLE
ERC725Z: Signatures

### ISSUE THREAD

**Issue by z0r0z** [ERC725Alliance/ERC725#138]
An implementation of smart account with 'shared' logic by verifying user signatures (v/r/s) to execute logic would helpfully extend this standard and instruct a DAO primitive.

Basically, the ERC725X + an extra param in execute() for user signature verification in contract.

**Comment by YamenMerhi** [comment]
Hey @z0r0z 
Thanks for opening an issue for this suggestion
IMO a smart contract executor should be generic enough to do just what it should do, which is normal execution.
This is something that is doable when building on top of the ERC725X.
If you check [LSP6-KeyManager](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-6-KeyManager.md), you have `executeRelayCall` function that offers an execution through ERC725X based on the signature, you could have also another smart contract that you create that function as the owner and can execute depending on whatever logic you want (signatures, permissions, etc..).
Opinions @CJ42 @frozeman ?
Happy to discuss further :)

**Comment by CJ42** [comment]
@z0r0z Does EIP1271 fit for this purpose? It can be used to verify signatures? 
If not, what is missing?

This is a standard library from OpenZeppelin
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/SignatureChecker.sol

But can be used as an interface that is inherited.

**Comment by z0r0z** [comment]
I am suggesting a standard form of `execute()` function where signature is provided as an extra param on top of ERC725X

**Comment by YamenMerhi** [comment]
Once again talking about this issue, it's up to @frozeman as he's the author of this standard, but I think it's too late to add another sub-standard. Also, I'm struggling to see the need to standardize a new type or sub-standard as this could be easily built on top, [LSP6-KeyManager](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-6-KeyManager.md) do it or even you can have a simpler version where you can have a contract owning the ERC725 and it check signatures and based on the check, the call will be executed. The erc725X is too generic so anything could be built on top.

Also in case of signature, you will implement nonces to prevent replay attacks but these nonces could be replayed (didn't test it but logical) if the contract was deployed with create2 and selfdestructed with delegatecall then recreated at the same address. Storage will be reset and nonces could be replayed. 

So IMO, any signature logic should be built on top of erc725X for security reasons and separation of concern.

**Comment by z0r0z** [comment]
thanks @YamenMerhi this makes sense

**Comment by frozeman** [comment]
@z0r0z an example of using `executeRelayCall()` of an LSP6 contract owning an EC725X can be found here:
https://docs.lukso.tech/guides/key-manager/execute-relay-call/
