### ISSUE TITLE
DApp like origin-playground

### ISSUE THREAD

**Issue by azizazlan** [ERC725Alliance/ERC725#38]
I want to create a (react)app like Origin-Playground, but this time using your latest ERC725 standards. I created a truffle project and install (npm install erc725). Something like the followings: 
```
import "erc725/contracts/ERC725/ERC725Account.sol";
 
contract ClaimHolder is ERC725Account, ERC734KeyManager {
    ...
}
```
Or in the client directory, I do npm install erc725 and directly use ERC725Account and ERC734KeyManager contracts?

**Comment by javieulate** [comment]
Hi @azizazlan , did you achieve it? Have you been able to run the original origin-playground app? I'm in the same situation.

**Comment by azizazlan** [comment]
> Hi @azizazlan , did you achieve it? Have you been able to run the original origin-playground app? I'm in the same situation.
Hi @javieulate Unfortunately no. However, I did managed to run the original origin-playground app.

**Comment by javieulate** [comment]
> > Hi @azizazlan , did you achieve it? Have you been able to run the original origin-playground app? I'm in the same situation.
> > Hi @javieulate Unfortunately no. However, I did managed to run the original origin-playground app.

And did you have to change something to do it so? I am having lots of problems when doing npm install & start. Thanks in advance!

**Comment by YamenMerhi** [comment]
Hey @azizazlan 
**ERC725Account** now is moved to the [lsp-smart-contract repo](https://github.com/lukso-network/lsp-smart-contracts).
**ERC734** is deprecated and replaced by [LSP6-KeyManager](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-6-KeyManager.md).
