### ISSUE TITLE
Discussion: should we have `operationType` in the `execute` function?

### ISSUE THREAD

**Issue by tyleryasaka** [ERC725Alliance/ERC725#6]
This is regarding the [ERC734 spec](https://github.com/ERC725Alliance/erc725/blob/master/docs/ERC-734.md).

This would update the `execute` function signature as such:

```
function execute(uint256 _operationType, address _to, uint256 _value, bytes _data) returns (uint256 executionId)
```

This would make the method more flexible. It would allow contract creation and use of `delegatecall`. This parameter exists on the current draft of the new ERC725: https://github.com/ERC725Alliance/erc725/blob/master/docs/ERC-725.md#execute

The downside is that it may be unnecessary for most use cases and it will use up another parameter and variable. Any thoughts?

**Comment by CPerezz** [comment]
Well, sounds good @tyleryasaka . I think provides good ways to operate from your Identity Contract. Which at the end is what you need right? Being able to execut code or functions of other contracts from your ID to leave some kind of Register. 

For me adds value and should be updated.

**Comment by tyleryasaka** [comment]
Thanks for the feedback @CPerezz. I apologize; this issue was not described well. I just updated this issue to clarify that I'm referring to ERC734 here.

ERC734 already has the *execute* function which can execute arbitrary contract calls in other contracts. What it cannot do, currently, is perform *delegatecall* operations or directly create contracts (see the `create` operation in [Solidity Assembly](https://solidity.readthedocs.io/en/v0.4.24/assembly.html). The *operationType* parameter would add this functionality. It's unclear to me and Fabian whether this is useful, so we wanted to get feedback from others.
